### ISSUE TITLE
坏档的样本

### ISSUE THREAD

**Issue by Supergenli** [burpheart/Palworld_Reverse_Note#4]
我本来也被坏档困扰着, 直到看到你这篇逆推笔记才发现解决方法

我看到你表示没有坏档的样本, 我手上现在正有一個专用伺服器坏档的样本
不知道你感兴趣或需要吗?

**Comment by Tardis07** [comment]
+1，我这里也有一份坏档的样本

**Comment by yamadafz** [comment]
我这里也有一份，我的情况是服务端开启后可以玩家可以进入游戏，但过了一阵子就无法进入游戏无限loading，在游戏内的玩家不受影响但只要退出了也是一样无法再进入服务器，然后服务器再一段时间（一天这样子）就会完全无法再进人了不管怎么重启服务器

**Comment by hapeman0314** [comment]
> 我这里也有一份，我的情况是服务端开启后可以玩家可以进入游戏，但过了一阵子就无法进入游戏无限loading，在游戏内的玩家不受影响但只要退出了也是一样无法再进入服务器，然后服务器再一段时间（一天这样子）就会完全无法再进人了不管怎么重启服务器

无限loading 可以试一下修改文件的权限 chmod -r 777 存档目录

**Comment by yamadafz** [comment]
> > 我这里也有一份，我的情况是服务端开启后可以玩家可以进入游戏，但过了一阵子就无法进入游戏无限loading，在游戏内的玩家不受影响但只要退出了也是一样无法再进入服务器，然后服务器再一段时间（一天这样子）就会完全无法再进人了不管怎么重启服务器
> 
> 无限loading 可以试一下修改文件的权限 chmod -r 777 存档目录

我是Windows端

**Comment by samyycX** [comment]
可以发我一份吗

**Comment by Tardis07** [comment]
> +1，我这里也有一份坏档的样本

[13.zip](https://github.com/burpheart/Palworld-Reverse-Note/files/14071529/13.zip)
这个存档在服务器启动后大约两分钟就会被覆盖为很小的文件，疑似重置了

**Comment by burpheart** [comment]
> > +1，我这里也有一份坏档的样本
> 
> [13.zip](https://github.com/burpheart/Palworld-Reverse-Note/files/14071529/13.zip) 这个存档在服务器启动后大约两分钟就会被覆盖为很小的文件，疑似重置了

这种情况应该是在存档尝试解压时就失败了 应该存档写入过程有中断   恢复出来的数据不一定完整
稍微修了下 试试能不能用
[Level1.zip](https://github.com/burpheart/Palworld-Reverse-Note/files/14081399/Level1.zip)

**Comment by burpheart** [comment]
> > > +1，我这里也有一份坏档的样本
> > 
> > 
> > [13.zip](https://github.com/burpheart/Palworld-Reverse-Note/files/14071529/13.zip) 这个存档在服务器启动后大约两分钟就会被覆盖为很小的文件，疑似重置了
> 
> 这种情况应该是在存档尝试解压时就失败了 应该存档写入过程有中断 恢复出来的数据不一定完整 稍微修了下 试试能不能用 [Level1.zip](https://github.com/burpheart/Palworld-Reverse-Note/files/14081399/Level1.zip)

跳过数据完整性校验 解压数据 在压缩回去

**Comment by Supergenli** [comment]
[palworld.zip](https://github.com/burpheart/Palworld-Reverse-Note/files/14084334/palworld.zip)
想請問一下，
这里是一个坏档，原因是退工会后导致坏掉不能再登入成功，一直卡读取LOADING画面
角色名字: 月落
多翻测试后(租了2個不同服, 用同一個伺服器端去測試)，找出壞掉的角色SAV应该是这个：07CFFD9A000000000000000000000000
如果直接在Level中删除掉有关角色的资料，然后伺服器终端再删除这个角色sav
是否就应该能实现移除角色并能成功重生登录?

**Comment by GalileoFe** [comment]
我这里也有好几份坏档、之前朋友找我希望我能帮忙恢复的。
同时正在研究相关问题。如果有进展希望大家可以多多交流。

这些存档全都是因为服务器突然中断导致的错误。
[人物存档因为服务器突然中断被洗成空文件.zip](https://github.com/burpheart/Palworld-Reverse-Note/files/14084364/default.zip)
[Pal(Level.Sav无法正常识别).zip](https://github.com/burpheart/Palworld-Reverse-Note/files/14084375/Pal.Level.Sav.zip)
[metoo(Level.sav无法正常识别).tar.gz](https://github.com/burpheart/Palworld-Reverse-Note/files/14084377/metoo.Level.sav.tar.gz)

**Comment by GalileoFe** [comment]
这里有另一种典型。
Level.sav文件不被Zlib视为压缩文件。
二进制看了一下改文件头理所当然不行。

```bash
`Traceback (most recent call last):
  File "D:\PalRepairKit\fix-host-save.py", line 244, in <module>
    main()
  File "D:\PalRepairKit\fix-host-save.py", line 75, in main
    sav_to_json(uesave_path, level_sav_path)
  File "D:\PalRepairKit\fix-host-save.py", line 162, in sav_to_json
    uncompressed_data = zlib.decompress(data[12:])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
zlib.error: Error -3 while decompressing data: invalid code lengths set
   ♥ 21:49:34  CPU: 50% | RAM: 32/63GB   350ms `
```

[Level.sav格式错误.zip](https://github.com/burpheart/Palworld-Reverse-Note/files/14084999/Level.sav.zip)


使用各种方式也无法调用Zlib解压。哎。头疼

**Comment by Guanchishan** [comment]
我也坏档了，[v0.3.3](https://store.steampowered.com/news/app/1623730/view/4222769301404625328?l=schinese)，一登进去就要我新建角色。
